language: go
go:
- 1.13.x
env:
  global:
  - GOPROXY=https://proxy.golang.org
  - GO111MODULE=on
  - secure: mhYjgWBH12l2oc/C9DftK7kCRG24CXJSiB0902uSMHGUForDHWvImsbOTSS2bA/fKYUu9psLygjo/9Z1uMXMNeRMeEig2GLvWVOyRB1cvgbCCTCN5I/sKEmucjszcM9FVUXOm3j2wJBkMLSdI7gvznMtIV99NfpErdEIz/id9oCMDA8z8A6LfCslsr6WOhVVpWQSKJdWOpbtYvKd7awcSgD6wpXaV8/q15D8yXpGiah18yZvuiNhQmhvKPjNJeGsG7Hz2znjAqqC9W6LM7UhqJ85AJ+85XGtcdzg+f4Bxb2C47vLWw1HSLleqL4xYmnLEqYr/0jk7tuaXb4JhkcP0yC+aFalwMY1muf9ZEbTNWjsZZ84r1E/8sKXb7qk+V4BMmdwbLDmqJkwl/T2FMXnfsPDXs/DsSJkU4CsQIS2A4sD/RLbu91eDl9LFRE6XbmGi9uCcKCsZrGsRnsCs0O982Xx26mJET+CNcrUG+impUVQyYZcF/8IzRNYQt8EnVBOI1/E8jKlJosk8i+biIeKVOjlKXD4qpvp4j2dimzVavQf+14DWg6MIUUIdgmGYsSmdHme2HGPm+eE5bgJSyCitP9VdiuQRIRIPdNIBjtl9pPB3Ys0ZM8XqnnDVXB5w9xXcv5paVU5yLXPuBY1i8TQde+cqq3XlyWhOVXm/mvFpek=
script:
- go run .ci/prebuild/gofmt_check.go
- go test -v ./...
- go run .ci/build/build.go
before_deploy:
- sudo snap install --classic goreleaser
- export PUBLISH=true
deploy:
- provider: script
  skip_cleanup: true
  script: go run .ci/deploy/travis_deploy.go
  on:
    repo: vmware-tanzu/crash-diagnostics
    all_branches: true
