language: go
go:
- 1.13.x
env:
  global:
  - GOPROXY=https://proxy.golang.org
  - GO111MODULE=on
  - secure: U22KqVjqN/vyTSVLuIU8H8koKJLCjP+xtc4mHUmFa/1Pfx9et0OTfoWp14fWLIJTBEnz8UIoQqbAbBMRRWgiqd9kGh/ByNX2ePfvmusA8hkozjaKKOtpMKVDOgWewj8PRt5Vxd17KMVo6Fsk3oo0O8wTydHwtJYl8Lac1lXlJYw//LQS0jdELTJwcgOuZtIfBfdv79dTLinNAtyA8Z7XUMCtQhVvp14BqRGlSDy3dKbjK15j551DJjHzCca65nO6+dFKbIbeODwOfFppfhLXuZZQeq69jFDPIZ7S4wqi4QLfJp108vfInAt23rv2wjcaEz4fwYGWmNTGOvXtrDhqcqQDPbESyLNQ9Wii/jw7eMgV2LVe23b5fXAH6Jwad0NTeap1iZ1ZTPRQP3rqCi/HtXnmXHFQCjTSAjc+SfOrzov0Q/IRVZumJ3QQuoYYUMwsiQ7XONrX97c1sWeFXmKrhJFi8A/x9HsdJXL/RhzqT55qN2ro143WR+WIUNuZJcdWTVnBfAdmXRj0h7XljqpG64PLKSTrBUOVkYxa5tyWMY9On13uwwbuLb7EupyNFW6oawPBsYQtFTfCkx5SJv2xNDvxlBfQ3aXkBA85Ezs1f3ju3UdV3BGO1dMnGuBBdVRC6Tg/BKNRp9CCBS+sWUeKFep7l/8gTIhmZOmjMT8hmRw=
script:
- go run .ci/prebuild/gofmt_check.go
- go test -v ./...
- go run .ci/build/build.go
before_deploy:
  - sudo snap install --classic goreleaser
  - export PUBLISH=true
deploy:
- provider: script
  skip_cleanup: true
  script: go run .ci/deploy/travis_deploy.go
  on:
    repo: vmware-tanzu/crash-diagnostics
    all_branches: true
