language: go

go:
  - 1.13.x

env:
  global:
    - GOPROXY=https://proxy.golang.org
    - GO111MODULE=on

script:
  - go run .ci/prebuild/gofmt_check.go
  - go test -v ./...
  - go run .ci/build/build.go