name: Crash Diagnostics Release

on:
  push:
    tags:
      - 'v*.*.**'

jobs:
  go-release:
    name: goreleaser-release
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@master
      -
        name: Set up Go
        uses: actions/setup-go@master
        with:
          go-version: 1.13.x
      -
        name: gofmt-check
        run: GO111MODULE=on go run .ci/prebuild/gofmt_check.go
      -
        name: Binary release
        uses: goreleaser/goreleaser-action@v1.1.0
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
